import type {
  CatalogRailDefinition,
  CatalogRailSurface,
  CatalogRailType,
} from '../domain/catalog-rail.types';

const HOME_GENRE_RAILS: CatalogRailDefinition[] = [
  {
    id: 'home_genre_action',
    title: 'Action',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { genre: 'ACTION', sort: 'viewCount', limit: 16 },
    link: '/films?genre=ACTION',
  },
  {
    id: 'home_genre_comedy',
    title: 'Comédie',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { genre: 'COMEDIE', sort: 'viewCount', limit: 16 },
    link: '/films?genre=COMEDIE',
  },
  {
    id: 'home_genre_drama',
    title: 'Drame',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { genre: 'DRAME', sort: 'viewCount', limit: 16 },
    link: '/films?genre=DRAME',
  },
  {
    id: 'home_genre_romance',
    title: 'Romance',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { genre: 'ROMANCE', sort: 'viewCount', limit: 16 },
    link: '/films?genre=ROMANCE',
  },
  {
    id: 'home_genre_thriller',
    title: 'Thriller',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { genre: 'THRILLER', sort: 'viewCount', limit: 16 },
    link: '/films?genre=THRILLER',
  },
];

function catalogGenreRails(
  surface: CatalogRailSurface,
  contentType: string,
  sectionTitle: string,
  basePath: string,
): CatalogRailDefinition[] {
  const rows: CatalogRailDefinition[] = [
    {
      id: `${surface}_catalog`,
      title: 'Tout le catalogue',
      surfaces: [surface],
      type: 'query' as CatalogRailType,
      hideIfEmpty: true,
      query: {
        contentType,
        sort: 'viewCount',
        limit: 24,
      },
      link: basePath,
      titleMode: 'plain',
    },
    {
      id: `${surface}_spotlight`,
      title: 'À ne pas manquer',
      surfaces: [surface],
      type: 'query' as CatalogRailType,
      hideIfEmpty: true,
      query: {
        contentType,
        sort: 'viewCount',
        limit: 18,
      },
      link: `${basePath}?sort=viewCount`,
    },
    {
      id: `${surface}_new`,
      title: 'Nouveautés',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: {
        contentType,
        sort: 'publishedAt',
        publishedWithinDays: 90,
        limit: 18,
      },
      link: `${basePath}?sort=publishedAt`,
      titleMode: 'plain',
    },
    {
      id: `${surface}_action_aventure`,
      title: 'Action et aventure',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: {
        contentType,
        genreCodes: ['ACTION', 'AVENTURE'],
        sort: 'viewCount',
        limit: 18,
      },
      link: `${basePath}?genre=ACTION`,
      titleMode: 'with-section',
    },
    {
      id: `${surface}_comedie`,
      title: 'Comédie',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: { contentType, genre: 'COMEDIE', sort: 'viewCount', limit: 18 },
      link: `${basePath}?genre=COMEDIE`,
      titleMode: 'with-section',
    },
    {
      id: `${surface}_drame`,
      title: 'Drame',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: { contentType, genre: 'DRAME', sort: 'viewCount', limit: 18 },
      link: `${basePath}?genre=DRAME`,
      titleMode: 'with-section',
    },
    {
      id: `${surface}_romance`,
      title: 'Romance',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: { contentType, genre: 'ROMANCE', sort: 'viewCount', limit: 18 },
      link: `${basePath}?genre=ROMANCE`,
      titleMode: 'with-section',
    },
    {
      id: `${surface}_thriller`,
      title: 'Thriller & suspense',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: {
        contentType,
        genreCodes: ['THRILLER', 'POLICIER'],
        sort: 'viewCount',
        limit: 18,
      },
      link: `${basePath}?genre=THRILLER`,
      titleMode: 'with-section',
    },
    {
      id: `${surface}_famille`,
      title: 'Famille',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: { contentType, genre: 'FAMILLE', sort: 'viewCount', limit: 18 },
      link: `${basePath}?genre=FAMILLE`,
      titleMode: 'with-section',
    },
    {
      id: `${surface}_documentaire`,
      title: 'Documentaire & culture',
      surfaces: [surface],
      type: 'query',
      hideIfEmpty: true,
      query: {
        contentType,
        genre: 'DOCUMENTAIRE',
        sort: 'viewCount',
        limit: 18,
      },
      link: `${basePath}?genre=DOCUMENTAIRE`,
      titleMode: 'with-section',
    },
  ];
  return rows.map((rail) => ({
    ...rail,
    subtitle: sectionTitle,
  }));
}

/** Registre central — unique source de vérité des rails iVOD. */
export const CATALOG_RAILS_REGISTRY: CatalogRailDefinition[] = [
  /* ── Personnalisés (accueil) ── */
  {
    id: 'continue_watching',
    title: 'Continuer à regarder',
    surfaces: ['home'],
    type: 'personalized',
    personalizedKind: 'continue_watching',
    requiresAuth: true,
    hideIfEmpty: true,
  },
  {
    id: 'resume_tonight',
    title: 'Reprends ce soir',
    surfaces: ['home'],
    type: 'personalized',
    personalizedKind: 'resume_tonight',
    requiresAuth: true,
    hideIfEmpty: true,
  },
  {
    id: 'unfinished',
    title: 'Séries en cours',
    surfaces: ['home', 'series'],
    type: 'personalized',
    personalizedKind: 'unfinished',
    requiresAuth: true,
    hideIfEmpty: true,
  },
  {
    id: 'my_list',
    title: 'Ma liste',
    surfaces: ['home'],
    type: 'personalized',
    personalizedKind: 'my_list',
    requiresAuth: true,
    hideIfEmpty: true,
  },
  {
    id: 'recommendations',
    title: 'Pour vous',
    surfaces: ['home'],
    type: 'personalized',
    personalizedKind: 'recommendations',
    requiresAuth: true,
    hideIfEmpty: true,
    link: '/recommendations',
  },

  /* ── Découverte (accueil) ── */
  {
    id: 'new_releases',
    title: 'Nouveautés',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { sort: 'publishedAt', limit: 20 },
    link: '/films?sort=publishedAt',
  },
  {
    id: 'trending',
    title: 'Tendances',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { sort: 'viewCount', publishedWithinDays: 30, limit: 20 },
    link: '/films?sort=viewCount',
  },
  {
    id: 'exclusives',
    title: 'Exclusivités iVOD',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { isExclusive: true, sort: 'viewCount', limit: 16 },
    link: '/films?sort=viewCount',
  },
  {
    id: 'made_in_ci',
    title: 'Made in Côte d\'Ivoire',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { countryOfOrigin: 'CI', sort: 'viewCount', limit: 16 },
    link: '/films?country=CI',
  },

  /* ── Par format (accueil) ── */
  {
    id: 'home_films',
    title: 'Films',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { contentType: 'FILM', sort: 'viewCount', limit: 20 },
    link: '/films',
  },
  {
    id: 'home_series',
    title: 'Séries',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { contentType: 'SERIE', sort: 'viewCount', limit: 20 },
    link: '/series',
  },
  {
    id: 'home_web_series',
    title: 'Web-séries',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { contentType: 'WEB_SERIE', sort: 'publishedAt', limit: 16 },
    link: '/web-series',
  },
  {
    id: 'home_animation',
    title: 'Animation',
    surfaces: ['home'],
    type: 'query',
    hideIfEmpty: true,
    query: { contentType: 'ANIMATION', sort: 'viewCount', limit: 16 },
    link: '/animation',
  },

  ...HOME_GENRE_RAILS,

  /* ── Pages catalogue dédiées ── */
  ...catalogGenreRails('films', 'FILM', 'Films', '/films'),
  ...catalogGenreRails('series', 'SERIE', 'Séries TV', '/series'),
  ...catalogGenreRails('web-series', 'WEB_SERIE', 'Web-séries', '/web-series'),
  ...catalogGenreRails('animation', 'ANIMATION', 'Animation', '/animation'),
];

export const CATALOG_SURFACE_SECTION_TITLES: Record<
  Exclude<CatalogRailSurface, 'home'>,
  string
> = {
  films: 'Films',
  series: 'Séries TV',
  'web-series': 'Web-séries',
  animation: 'Animation',
};
